### ISSUE TITLE
save_screenshot does not overwrite screenshot.png

### ISSUE THREAD

**Issue by mikalindh** [qentinelqi/qweb#22] opened 2021-06-10 04:51 UTC
**Describe the bug**
ClickIcon makes comparison against screenshot.png.
However this only works once as save_screenshot is not overwriting screenshot.png when new is taken but renames those as screenshot_000, etc.. If there is multiple Icon related keywords in test suite those latter ones are failing because of this.

I believe this only happens in Linux and is pyautogui/scrot -related issue with newer Python versions (at least i haven't noticed it before with older versions).

**Comment by tkoukkari** [comment] 2021-06-10 14:02
Hi,
Thanks for reporting this. I may not understand the use case fully. Can you elaborate it a bit? Any snippet of script that could reproduce this?

Best regards,
Tuomas

**Comment by mikalindh** [comment] 2021-06-11 10:27
I dont have log (this came from customer) and it's already fixed using workaround but i am trying to explain:

We have script like this:
ClickIcon   some_image
Do something else
ClickIcon   some_other_image

Now when we reach that first ClickIcon it takes screenshot.png and after that makes comparision if screenshot.png matches to some_image = all is good. 
Problem appears when we reach ClickIcon some_other_image. It again takes screenshot, but as we already have screenshot.png in our folder it names this new one to screenshot_000.png instead of overwriting screenshot.png. However comparision is still made against screenshot.png, which in this case is obviously wrong picture and we are getting Fail.

**Comment by mikalindh** [comment] 2021-06-11 10:31
I believe combination where this happened was Ubuntu, Python 3.7 or 3.8 and newest QWeb

**Comment by tkoukkari** [comment] 2021-06-11 11:58
Ok, thanks for the clarification. Sounds weird, but we'll debug this.

**Comment by tkoukkari** [comment] 2021-06-15 18:13
Could not repro this with Ubuntu and python 3.7/3.8. Turns out you need a newer scrot version which is included in Ubuntu 20; the default operation of scrot is different.

Since this is not yet fixed in pyautogui, we fixed this by removing the file. Fix should be included in release **1.0.5** later this week.

**Closed as completed by tkoukkari** 2021-06-15 18:13 UTC
Labels: bug
